export type FunnelLocale = 'zh-Hant' | 'en' | 'zh-Hans';

export const CAAC_FUNNEL = {
  slug: 'caac-m-150kg',
  name: 'CAAC-M 150Kg 無人機牌照課程和考試',
  originalPrice: 23400,
  salePrice: 18000,
  bonusValue: 1800,
  currency: 'HKD'
} as const;

export const funnelCopy = {
  'zh-Hant': {
    language: '繁體中文',
    eyebrow: 'CAAC-M 150Kg 無人機牌照課程和考試',
    heroTitle: '從了解要求，到完成報名與考試安排',
    heroBody: '一個清楚、可追蹤的報讀流程。先取得免費電子書，再預約課程諮詢，確認適合後才付款。',
    ebookCta: '免費取得課程電子書',
    consultCta: '預約免費諮詢',
    priceLabel: '現時優惠價',
    originalLabel: '原價',
    bonusLabel: '報名贈品',
    bonusTitle: '考試禁區考察團',
    bonusValue: '價值 HK$1,800',
    ebookTitle: '先下載免費電子書',
    ebookBody: '留下聯絡資料後，系統會記錄你的報讀興趣並顯示電子書下載入口。',
    name: '姓名',
    email: 'Email',
    phone: '電話／WhatsApp',
    role: '職業／公司／學校',
    consent: '我同意私隱政策，並同意接收這個課程的跟進資料。',
    submit: '取得電子書',
    submitting: '正在提交…',
    success: '提交成功！你可以下載電子書，或繼續預約諮詢。',
    download: '下載電子書 PDF',
    journeyTitle: 'AiLAE 如何協助你完成報讀',
    journey: ['取得電子書', '預約 Calendly 諮詢', '確認資格與安排', 'Stripe／FPS 付款', '收到入學指引'],
    includedTitle: '報名後包括',
    included: ['CAAC-M 150Kg 課程及考試安排', '課程電子書 PDF', 'AiLAE 報名及學習提醒', 'Calendly 課前諮詢', '考試禁區考察團（贈品）'],
    verifyTitle: '正式發布前需要由負責人確認',
    verify: ['課時、上課地點和考試日期', '報名資格、退款及改期政策', '考試機構及牌照陳述的正式依據', '考察團日期、集合地點、名額和安全安排'],
    faqTitle: '常見疑問',
    faqs: [
      ['我是否符合報名資格？', '先填寫簡短資料，再透過 Calendly 預約諮詢，由課程顧問確認。'],
      ['如何付款？', '可選 Stripe 信用卡或 FPS。Stripe 成功後即時確認；FPS 需按流程核對。'],
      ['網站支援哪些語言？', '繁體中文、英文及簡體中文可以即時切換。']
    ],
    finalTitle: '準備了解 CAAC-M 150Kg 課程？',
    finalBody: '先取得免費電子書。資料確認後，再決定是否預約或報名。',
    privacy: '私隱政策',
    terms: '條款及細則'
  },
  en: {
    language: 'English',
    eyebrow: 'CAAC-M 150Kg UAV Licence Course & Examination',
    heroTitle: 'A clear path from eligibility to enrolment and examination',
    heroBody: 'Download the free guide, book a consultation, confirm the arrangements and only then proceed to payment.',
    ebookCta: 'Get the free course eBook',
    consultCta: 'Book a free consultation',
    priceLabel: 'Current offer',
    originalLabel: 'Original price',
    bonusLabel: 'Enrolment bonus',
    bonusTitle: 'Examination restricted-zone study tour',
    bonusValue: 'Value HK$1,800',
    ebookTitle: 'Download the free eBook first',
    ebookBody: 'Leave your contact details to receive the download link and course follow-up.',
    name: 'Name',
    email: 'Email',
    phone: 'Phone / WhatsApp',
    role: 'Occupation / company / school',
    consent: 'I agree to the privacy policy and to receive follow-up information about this course.',
    submit: 'Get the eBook',
    submitting: 'Submitting…',
    success: 'Submitted. You can download the eBook or book a consultation.',
    download: 'Download the PDF eBook',
    journeyTitle: 'How AiLAE supports your enrolment journey',
    journey: ['Get the eBook', 'Book via Calendly', 'Confirm eligibility', 'Pay by Stripe / FPS', 'Receive onboarding'],
    includedTitle: 'Your enrolment includes',
    included: ['CAAC-M 150Kg course and examination arrangements', 'Course eBook PDF', 'AiLAE enrolment and learning reminders', 'Pre-course Calendly consultation', 'Restricted-zone study tour bonus'],
    verifyTitle: 'Items the course owner must confirm before launch',
    verify: ['Course hours, venue and examination date', 'Eligibility, refund and rescheduling policies', 'Formal basis for examination and licence claims', 'Study-tour date, meeting point, capacity and safety arrangements'],
    faqTitle: 'Frequently asked questions',
    faqs: [
      ['Am I eligible?', 'Submit the short form and book a Calendly consultation for an eligibility check.'],
      ['How can I pay?', 'Choose Stripe card payment or FPS. Stripe is confirmed immediately; FPS requires verification.'],
      ['Which languages are supported?', 'Traditional Chinese, English and Simplified Chinese can be switched instantly.']
    ],
    finalTitle: 'Ready to learn about the CAAC-M 150Kg course?',
    finalBody: 'Start with the free eBook, then decide whether to book or enrol.',
    privacy: 'Privacy',
    terms: 'Terms'
  },
  'zh-Hans': {
    language: '简体中文',
    eyebrow: 'CAAC-M 150Kg 无人机执照课程和考试',
    heroTitle: '从了解要求，到完成报名与考试安排',
    heroBody: '清楚、可追踪的报读流程。先取得免费电子书，再预约课程咨询，确认适合后才付款。',
    ebookCta: '免费取得课程电子书',
    consultCta: '预约免费咨询',
    priceLabel: '现时优惠价',
    originalLabel: '原价',
    bonusLabel: '报名赠品',
    bonusTitle: '考试禁区考察团',
    bonusValue: '价值 HK$1,800',
    ebookTitle: '先下载免费电子书',
    ebookBody: '留下联系资料后，系统会记录你的报读兴趣并显示电子书下载入口。',
    name: '姓名',
    email: 'Email',
    phone: '电话／WhatsApp',
    role: '职业／公司／学校',
    consent: '我同意隐私政策，并同意接收这个课程的跟进资料。',
    submit: '取得电子书',
    submitting: '正在提交…',
    success: '提交成功！你可以下载电子书，或继续预约咨询。',
    download: '下载电子书 PDF',
    journeyTitle: 'AiLAE 如何协助你完成报读',
    journey: ['取得电子书', '预约 Calendly 咨询', '确认资格与安排', 'Stripe／FPS 付款', '收到入学指引'],
    includedTitle: '报名后包括',
    included: ['CAAC-M 150Kg 课程及考试安排', '课程电子书 PDF', 'AiLAE 报名及学习提醒', 'Calendly 课前咨询', '考试禁区考察团（赠品）'],
    verifyTitle: '正式发布前需要由负责人确认',
    verify: ['课时、上课地点和考试日期', '报名资格、退款及改期政策', '考试机构及执照陈述的正式依据', '考察团日期、集合地点、名额和安全安排'],
    faqTitle: '常见问题',
    faqs: [
      ['我是否符合报名资格？', '先填写简短资料，再通过 Calendly 预约咨询，由课程顾问确认。'],
      ['如何付款？', '可选 Stripe 信用卡或 FPS。Stripe 成功后即时确认；FPS 需要核对。'],
      ['网站支持哪些语言？', '繁体中文、英文及简体中文可以即时切换。']
    ],
    finalTitle: '准备了解 CAAC-M 150Kg 课程？',
    finalBody: '先取得免费电子书。资料确认后，再决定是否预约或报名。',
    privacy: '隐私政策',
    terms: '条款及细则'
  }
} as const;

export function isFunnelLocale(value: string | null): value is FunnelLocale {
  return value === 'zh-Hant' || value === 'en' || value === 'zh-Hans';
}
