<script lang="ts">
  import { onMount } from 'svelte';
  import FunnelHeader from '$lib/components/Funnel/FunnelHeader.svelte';
  import { isFunnelLocale, type FunnelLocale } from '$lib/funnel/caac';
  let locale: FunnelLocale = 'zh-Hant';
  let reference = '';
  let method = '';
  const content = {
    'zh-Hant': { step:'步驟 5 / 5', title:'資料已收到', body:'AiLAE 已建立你的報名記錄。Stripe 付款成功後會即時確認；FPS 付款需要按正式核對流程確認。', next:'接下來請完成', items:['檢查確認 Email 並保存付款收據','完成個人資料和入學資格核對','查看課程、考試及考察團安排','加入 WhatsApp／客服支援群組'], home:'返回课程页面', support:'联络课程顾问' },
    en: { step:'Step 5 / 5', title:'Your details have been received', body:'AiLAE has created your enrolment record. Stripe is confirmed immediately after successful payment; FPS requires verification.', next:'Next steps', items:['Check the confirmation email and keep your receipt','Complete your profile and eligibility check','Review course, examination and study-tour arrangements','Join the WhatsApp or support group'], home:'Back to course', support:'Contact course adviser' },
    'zh-Hans': { step:'步骤 5 / 5', title:'资料已收到', body:'AiLAE 已建立你的报名记录。Stripe 付款成功后会即时确认；FPS 付款需要按正式核对流程确认。', next:'接下来请完成', items:['检查确认 Email 并保存付款收据','完成个人资料和入学资格核对','查看课程、考试及考察团安排','加入 WhatsApp／客服支持群组'], home:'返回课程页面', support:'联系课程顾问' }
  } as const;
  $: copy = content[locale];
  function setLocale(next:FunnelLocale){locale=next;localStorage.setItem('ailae-funnel-locale',next)}
  onMount(()=>{const saved=localStorage.getItem('ailae-funnel-locale');if(isFunnelLocale(saved))locale=saved;const params=new URLSearchParams(location.search);reference=params.get('order')||params.get('session_id')||'';method=params.get('method')||params.get('demo')||'stripe'});
</script>
<svelte:head><title>{copy.title} | AiLAE Funnel</title></svelte:head>
<div class="thanks-page"><FunnelHeader {locale} compact on:locale={(event)=>setLocale(event.detail)}/><main><section class="success"><div class="check">✓</div><p>{copy.step}</p><h1>{copy.title}</h1><span>{copy.body}</span>{#if reference}<dl><div><dt>Payment</dt><dd>{method.toUpperCase()}</dd></div><div><dt>Reference</dt><dd>{reference}</dd></div></dl>{/if}</section><section class="next"><p>NEXT STEPS</p><h2>{copy.next}</h2><ol>{#each copy.items as item,index}<li><span>{index+1}</span><b>{item}</b></li>{/each}</ol><div><a href="/f/caac-m-150kg">{copy.home}</a><a class="primary" href="/f/caac-m-150kg/booking">{copy.support}</a></div></section></main></div>
<style>:global(body){margin:0;background:#07101f}.thanks-page{min-height:100vh;background:radial-gradient(circle at 22% 20%,rgba(52,211,153,.18),transparent 28%),#07101f;color:white;font-family:Inter,system-ui,sans-serif}.thanks-page *{box-sizing:border-box}main{display:grid;grid-template-columns:.8fr 1.2fr;gap:70px;align-items:center;width:min(1080px,calc(100% - 40px));min-height:calc(100vh - 60px);margin:0 auto;padding:70px 0}.check{display:grid;width:84px;height:84px;place-items:center;border:1px solid rgba(52,211,153,.5);border-radius:50%;background:rgba(52,211,153,.12);color:#69e5ce;font-size:42px}.success>p,.next>p{margin:30px 0 10px;color:#69e5ce;font-size:11px;font-weight:900;letter-spacing:.18em}.success h1{margin:0;font-size:54px;line-height:1.05;letter-spacing:-.04em}.success>span{display:block;margin-top:20px;color:#a9bbca;line-height:1.7}.success dl{margin-top:30px;border-top:1px solid #24374a;padding-top:14px}.success dl div{display:flex;justify-content:space-between;padding:8px 0}.success dt{color:#8297a9}.success dd{margin:0;max-width:210px;overflow:hidden;text-overflow:ellipsis}.next{border:1px solid rgba(255,255,255,.12);border-radius:26px;background:rgba(255,255,255,.06);padding:42px}.next>p{margin-top:0}.next h2{font-size:32px}.next ol{padding:0;list-style:none}.next li{display:grid;grid-template-columns:44px 1fr;gap:14px;align-items:center;border-top:1px solid rgba(255,255,255,.1);padding:18px 0}.next li span{display:grid;width:36px;height:36px;place-items:center;border-radius:50%;background:#102d37;color:#69e5ce;font-size:12px}.next li b{font-size:14px}.next>div{display:flex;gap:10px;margin-top:24px}.next a{display:inline-flex;min-height:46px;align-items:center;border:1px solid #385064;border-radius:10px;padding:0 17px;color:white;font-weight:800;text-decoration:none}.next a.primary{border-color:transparent;background:#13a88d;color:#041818}@media(max-width:800px){main{grid-template-columns:1fr;gap:36px}.success h1{font-size:43px}.next{padding:28px}}@media(max-width:520px){main{width:calc(100% - 28px)}.next>div{flex-direction:column}.next a{justify-content:center}}</style>
