const en = {
  flightTitle: 'Flight training results', flightType: 'Flight type', simulatorMode: 'Simulator', realMode: 'Real flight',
  screenshot: 'Results screenshot', recording: 'Flight recording', videoLink: 'Same-flight video Drive link (optional)',
  screenshotHelp: 'Submit the simulator results screenshot. AI reads only clearly visible scores and metrics.',
  pairHelp: 'Use the first link for a results screenshot. Add its flight recording below to combine both sources into one report. Both files must belong to the same flight.',
  crossCheck: 'Screenshot and video comparison', consistent: 'Visible evidence agrees', conflict: 'Conflicting evidence',
  pair_requires_image: 'When attaching a recording, the first link must be a JPG/PNG/WebP results screenshot.',
  pair_requires_video: 'The second link must be an MP4/WebM flight recording.',
  mine: 'My results', demo: 'Sample flights', title: 'Simulator results',
  subtitle: 'Google Drive submissions and personal AI reviews', help: 'Submission guide',
  name: 'Training title', link: 'Google Drive share link', scenario: 'Training scenario',
  consent: 'I own this recording or have permission to submit it. I consent to AI processing and saving my report.',
  importFile: 'Read file', analyze: 'Analyze with AI', importing: 'Reading shared file…', analyzing: 'Analyzing evidence…',
  extracting: 'Extracting frames', preview: 'Submission preview', numeric: 'Measured results', ai: 'AI feedback',
  good: 'Within target', improve: 'Needs improvement', unknown: 'Insufficient evidence',
  metric: 'Metric', value: 'Measured value', target: 'File target', deviation: 'Difference', status: 'Status',
  evidence: 'Evidence', advice: 'Next practice', limitations: 'Limitations',
  history: 'My submissions', empty: 'No submissions yet', open: 'View', remove: 'Delete', cancel: 'Cancel',
  confirmDelete: 'Delete this report? The original file in your Drive will remain.', more: 'Load more',
  download: 'Download report', template: 'CSV template', source: 'Original file', saved: 'Report saved',
  privacy: 'Only you can view these reports in AiLAE Class. Files shared through a public link remain accessible to anyone with that link.',
  reference: 'Practice feedback only. File targets are learner-provided, not verified instructor standards. Video analysis samples 12 still frames without audio; it cannot establish a complete flight or an official grade.',
  formats: 'MP4/H.264 or WebM: 100 MB, 20 min · JPG/PNG/WebP: 5 MB · CSV/JSON/Google Sheets: 2 MB, 200 metrics',
  guide1: 'Upload the recording, screenshot or results file to your own Google Drive.',
  guide2: 'Share only that file as “Anyone with the link · Viewer”, with downloading allowed. Avoid including personal or sensitive information.',
  guide3: 'Paste its link here, choose the scenario, then read the file and check the preview before requesting AI analysis.',
  guide4: 'For tabular data, use metric,value,unit,target,direction. Direction: lower (≤), higher (≥) or equal (=). Excel: export as CSV, or open it in Google Sheets and share that sheet.',
  invalidRows: 'Invalid rows', warnings: 'Rows requiring attention', reloadMedia: 'Re-import the Drive link to analyze this media again.',
  pending: 'Reading', imported: 'Ready for analysis', processing: 'Analyzing', completed: 'Completed', failed: 'Failed',
  frame: 'Frame', issues: 'Data quality', retry: 'Try again',
  invalid_link: 'Use a Google Drive file link or Google Sheets link. Folder links and other websites are not supported.',
  share_unavailable: 'The file cannot be downloaded. Check Viewer link sharing, download permission, and whether the file still exists.',
  unsupported_file: 'This format is not supported. Use MP4/WebM, JPG/PNG/WebP, CSV/JSON or Google Sheets. Export Excel/PDF data as CSV or a clear screenshot.',
  file_too_large: 'The file exceeds the size limit. Compress or split it and share again.',
  empty_file: 'The shared file is empty.', download_failed: 'Download timed out or was interrupted. Try a smaller file.',
  invalid_data: 'No valid numeric results were found. Check the CSV/JSON format and use the template.',
  columns_required: 'The data file needs metric and value columns. Use the CSV template.',
  too_many_metrics: 'Use no more than 200 metrics per submission.',
  unauthenticated: 'Please sign in again.', setup_required: 'Results storage is not enabled yet. Please contact the administrator.',
  storage_failed: 'The report could not be saved. Please try again.', rate_limit: 'Too many submissions. Try later (5 per 10 minutes, 30 per day).',
  invalid_request: 'Complete the title, link, scenario and consent before submitting.',
  analysis_failed: 'AI analysis did not complete. Your submission remains available; try again.',
  ai_unavailable: 'The required AI model is not configured. Contact the administrator; numeric previews remain available.',
  analysis_busy: 'Analysis is already running, or this submission has reached its 3-attempt limit.',
  invalid_frames: 'The extracted frames are invalid. Re-import the video and try again.',
  not_found: 'This report is unavailable for your account.',
  video_decode: 'This browser cannot decode the file. Convert the video to MP4/H.264 or use a JPG/PNG screenshot.',
  video_duration: 'Use a video with a readable duration of no more than 20 minutes.',
  invalid_value: 'Missing metric or invalid number', missing_standard: 'Missing target or comparison direction'
};

const zhTW: typeof en = {
  flightTitle: '飛行訓練成績', flightType: '飛行類型', simulatorMode: '模擬器', realMode: '實飛',
  screenshot: '成績截圖', recording: '飛行錄影', videoLink: '同一飛行的錄影 Drive 連結（選填）',
  screenshotHelp: '提交 Simulator 的成績畫面截圖，AI 只讀取清晰可見的分數與指標。',
  pairHelp: '第一個連結放成績截圖，下方可加入同一飛行的錄影。兩份資料會合併成一份報告，請確認它們來自同一次飛行。',
  crossCheck: '成績截圖與錄影核對', consistent: '可見證據相符', conflict: '證據有矛盾',
  pair_requires_image: '附加錄影時，第一個連結必須是 JPG／PNG／WebP 成績截圖。',
  pair_requires_video: '第二個連結必須是 MP4／WebM 飛行錄影。',
  mine: '我的成績', demo: '示範飛行', title: '模擬訓練成績', subtitle: 'Google Drive 提交與個人 AI 分析', help: '提交指引',
  name: '訓練名稱', link: 'Google Drive 分享連結', scenario: '訓練科目',
  consent: '此內容屬於我或已獲提交授權；我同意使用 AI 處理內容並儲存分析報告。',
  importFile: '讀取檔案', analyze: '開始 AI 分析', importing: '正在讀取分享檔案…', analyzing: '正在分析證據…', extracting: '正在擷取畫面',
  preview: '提交內容預覽', numeric: '實測數據', ai: 'AI 評語', good: '符合目標', improve: '需要改善', unknown: '資料不足',
  metric: '指標', value: '實際數值', target: '檔案目標', deviation: '差值', status: '狀態', evidence: '判斷依據', advice: '下次練習', limitations: '分析限制',
  history: '我的提交紀錄', empty: '尚未提交成績', open: '查看', remove: '刪除', cancel: '取消',
  confirmDelete: '確定刪除此報告？你在 Drive 的原始檔案會保留。', more: '載入更多', download: '下載報告', template: 'CSV 範本', source: '原始檔案', saved: '報告已儲存',
  privacy: 'AiLAE Class 內的報告只供本人查看。設為連結分享的 Drive 檔案，任何持有該連結的人仍可存取。',
  reference: '僅供訓練參考。數據檔內的目標由提交者提供，並非已核實的教師標準。影片取樣 12 張靜態畫面，不分析音訊；不能證明完整飛行表現，也不構成正式評分。',
  formats: 'MP4/H.264 或 WebM：100 MB、20 分鐘 · JPG/PNG/WebP：5 MB · CSV/JSON/Google 試算表：2 MB、200 個指標',
  guide1: '將影片、成績截圖或數據檔上傳到自己的 Google Drive。',
  guide2: '只將該檔案設為「知道連結的任何人 · 檢視者」，並允許下載。請先移除個人及敏感資料。',
  guide3: '在此貼上連結、選擇科目，讀取檔案並確認預覽，再開始 AI 分析。',
  guide4: '數據欄位使用 metric,value,unit,target,direction。方向：lower（≤）、higher（≥）、equal（=）。Excel 請匯出 CSV，或用 Google 試算表開啟後分享。',
  invalidRows: '無效資料列', warnings: '需要檢查的資料列', reloadMedia: '請重新讀取 Drive 連結後再分析此影片或圖片。',
  pending: '讀取中', imported: '等待分析', processing: '分析中', completed: '已完成', failed: '失敗', frame: '畫面', issues: '資料品質', retry: '重試',
  invalid_link: '請使用 Google Drive 檔案或 Google 試算表連結；不支援資料夾及其他網站。',
  share_unavailable: '無法下載檔案。請確認已開放檢視者連結分享、允許下載，而且檔案仍然存在。',
  unsupported_file: '不支援此格式。請使用 MP4/WebM、JPG/PNG/WebP、CSV/JSON 或 Google 試算表。Excel／PDF 成績可匯出 CSV 或清晰截圖。',
  file_too_large: '檔案超出大小限制，請壓縮或分拆後重新分享。', empty_file: '分享檔案沒有內容。', download_failed: '下載逾時或中斷，請重試或縮小檔案。',
  invalid_data: '找不到有效的數值成績，請核對 CSV／JSON 格式或使用範本。', columns_required: '數據需要 metric 及 value 欄位，請使用 CSV 範本。', too_many_metrics: '每次最多提交 200 個指標。',
  unauthenticated: '登入已失效，請重新登入。', setup_required: '成績儲存尚未啟用，請聯絡管理員。', storage_failed: '未能儲存報告，請重試。', rate_limit: '提交過於頻繁，請稍後再試（每 10 分鐘 5 次，每天 30 次）。',
  invalid_request: '請填寫名稱、連結、科目並確認處理同意。', analysis_failed: 'AI 分析未完成，已保留提交紀錄，可以重試。',
  ai_unavailable: '所需的 AI 模型尚未設定，請聯絡管理員；數據預覽仍可查看。', analysis_busy: '分析正在進行，或此紀錄已達 3 次嘗試上限。',
  invalid_frames: '擷取的畫面無效，請重新讀取影片後再試。', not_found: '此帳號無法存取該報告。', video_decode: '瀏覽器無法解碼檔案。請將影片轉成 MP4/H.264，或使用 JPG／PNG 截圖。', video_duration: '請使用長度可讀取且不超過 20 分鐘的影片。',
  invalid_value: '缺少指標或數字無效', missing_standard: '缺少目標或比較方向'
};

// Kept local to the new module so existing translation edits remain untouched.
const localized: Record<string, Partial<typeof en>> = {
  'zh-TW': zhTW,
  zh: { ...zhTW, mine: '我的成绩', demo: '示范飞行', title: '模拟训练成绩', subtitle: 'Google Drive 提交与个人 AI 分析', help: '提交指引', name: '训练名称', link: 'Google Drive 分享链接', scenario: '训练科目', consent: '此内容属于我或已获提交授权；我同意使用 AI 处理内容并保存分析报告。', importFile: '读取文件', analyze: '开始 AI 分析', importing: '正在读取分享文件…', analyzing: '正在分析证据…', extracting: '正在提取画面', preview: '提交内容预览', numeric: '实测数据', ai: 'AI 评语', good: '符合目标', improve: '需要改善', unknown: '数据不足', metric: '指标', value: '实际数值', target: '文件目标', deviation: '差值', status: '状态', evidence: '判断依据', advice: '下次练习', limitations: '分析限制', history: '我的提交记录', empty: '尚未提交成绩', open: '查看', remove: '删除', cancel: '取消', confirmDelete: '确定删除此报告？你在 Drive 的原始文件会保留。', more: '加载更多', download: '下载报告', template: 'CSV 模板', source: '原始文件', saved: '报告已保存', pending: '读取中', imported: '等待分析', processing: '分析中', completed: '已完成', failed: '失败', frame: '画面', issues: '数据质量', retry: '重试', invalidRows: '无效数据行', warnings: '需要检查的数据行', reloadMedia: '请重新读取 Drive 链接后再分析此视频或图片。' },
  ms: { mine: 'Keputusan saya', demo: 'Penerbangan contoh', title: 'Keputusan simulator', subtitle: 'Penyerahan Google Drive dan ulasan AI peribadi', help: 'Panduan penyerahan', name: 'Nama latihan', link: 'Pautan perkongsian Google Drive', scenario: 'Senario latihan', consent: 'Saya memiliki kandungan ini atau mendapat kebenaran. Saya bersetuju dengan pemprosesan AI dan penyimpanan laporan.', importFile: 'Baca fail', analyze: 'Analisis dengan AI', importing: 'Membaca fail…', analyzing: 'Menganalisis bukti…', preview: 'Pratonton', good: 'Mencapai sasaran', improve: 'Perlu diperbaiki', unknown: 'Bukti tidak mencukupi', history: 'Penyerahan saya', open: 'Lihat', remove: 'Padam', cancel: 'Batal', download: 'Muat turun laporan', saved: 'Laporan disimpan' },
  id: { mine: 'Hasil saya', demo: 'Contoh penerbangan', title: 'Hasil simulator', subtitle: 'Kiriman Google Drive dan ulasan AI pribadi', help: 'Panduan pengiriman', name: 'Nama latihan', link: 'Tautan berbagi Google Drive', scenario: 'Skenario latihan', consent: 'Saya memiliki konten ini atau mendapat izin. Saya menyetujui pemrosesan AI dan penyimpanan laporan.', importFile: 'Baca berkas', analyze: 'Analisis dengan AI', importing: 'Membaca berkas…', analyzing: 'Menganalisis bukti…', preview: 'Pratinjau', good: 'Sesuai target', improve: 'Perlu perbaikan', unknown: 'Bukti tidak cukup', history: 'Kiriman saya', open: 'Lihat', remove: 'Hapus', cancel: 'Batal', download: 'Unduh laporan', saved: 'Laporan tersimpan' },
  hi: { mine: 'मेरे परिणाम', demo: 'उड़ान उदाहरण', title: 'सिम्युलेटर परिणाम', subtitle: 'Google Drive सबमिशन और व्यक्तिगत AI समीक्षा', help: 'जमा करने की गाइड', name: 'अभ्यास का नाम', link: 'Google Drive शेयर लिंक', scenario: 'अभ्यास परिदृश्य', consent: 'यह सामग्री मेरी है या मुझे अनुमति है। मैं AI द्वारा प्रसंस्करण और रिपोर्ट सहेजने के लिए सहमत हूँ।', importFile: 'फ़ाइल पढ़ें', analyze: 'AI से विश्लेषण करें', importing: 'फ़ाइल पढ़ी जा रही है…', analyzing: 'साक्ष्य का विश्लेषण…', preview: 'पूर्वावलोकन', good: 'लक्ष्य के अनुरूप', improve: 'सुधार आवश्यक', unknown: 'अपर्याप्त साक्ष्य', history: 'मेरे सबमिशन', open: 'देखें', remove: 'हटाएँ', cancel: 'रद्द करें', download: 'रिपोर्ट डाउनलोड करें', saved: 'रिपोर्ट सहेजी गई' },
  th: { mine: 'ผลของฉัน', demo: 'ตัวอย่างการบิน', title: 'ผลการฝึกจำลอง', subtitle: 'การส่ง Google Drive และการวิเคราะห์ AI ส่วนตัว', help: 'คำแนะนำการส่ง', name: 'ชื่อการฝึก', link: 'ลิงก์แชร์ Google Drive', scenario: 'สถานการณ์ฝึก', consent: 'ฉันเป็นเจ้าของเนื้อหาหรือได้รับอนุญาต และยินยอมให้ AI ประมวลผลและบันทึกรายงาน', importFile: 'อ่านไฟล์', analyze: 'วิเคราะห์ด้วย AI', importing: 'กำลังอ่านไฟล์…', analyzing: 'กำลังวิเคราะห์หลักฐาน…', preview: 'ตัวอย่าง', good: 'ตรงตามเป้าหมาย', improve: 'ควรปรับปรุง', unknown: 'หลักฐานไม่เพียงพอ', history: 'รายการส่งของฉัน', open: 'ดู', remove: 'ลบ', cancel: 'ยกเลิก', download: 'ดาวน์โหลดรายงาน', saved: 'บันทึกรายงานแล้ว' }
};

const extra: Record<string, Partial<typeof en>> = {
  zh: {
    flightTitle: '飞行训练成绩', flightType: '飞行类型', simulatorMode: '模拟器', realMode: '实飞', screenshot: '成绩截图', recording: '飞行录像', videoLink: '同一飞行的录像 Drive 链接（选填）',
    screenshotHelp: '提交 Simulator 的成绩画面截图，AI 只读取清晰可见的分数与指标。', pairHelp: '第一个链接放成绩截图，下方可加入同一飞行的录像。两份数据会合并成一份报告，请确认它们来自同一次飞行。', crossCheck: '成绩截图与录像核对', consistent: '可见证据相符', conflict: '证据有矛盾', pair_requires_image: '附加录像时，第一个链接必须是 JPG／PNG／WebP 成绩截图。', pair_requires_video: '第二个链接必须是 MP4／WebM 飞行录像。',
    privacy: 'AiLAE Class 内的报告只供本人查看。设为链接分享的 Drive 文件，任何持有该链接的人仍可访问。',
    reference: '仅供训练参考。文件中的目标由提交者提供，并非已核实的教师标准。视频取样 12 张静态画面，不分析音频；不能证明完整飞行表现，也不构成正式评分。',
    formats: 'MP4/H.264 或 WebM：100 MB、20 分钟 · JPG/PNG/WebP：5 MB · CSV/JSON/Google 表格：2 MB、200 个指标',
    guide1: '将视频、成绩截图或数据文件上传到自己的 Google Drive。',
    guide2: '只将该文件设为“知道链接的任何人 · 查看者”，并允许下载。请先移除个人及敏感信息。',
    guide3: '在此粘贴链接、选择科目，读取文件并确认预览，再开始 AI 分析。',
    guide4: '数据字段使用 metric,value,unit,target,direction。方向：lower（≤）、higher（≥）、equal（=）。Excel 请导出 CSV，或用 Google 表格打开后分享。',
    invalid_link: '请使用 Google Drive 文件或 Google 表格链接；不支持文件夹及其他网站。',
    share_unavailable: '无法下载文件。请确认已开放查看者链接分享、允许下载，而且文件仍然存在。',
    unsupported_file: '不支持此格式。请使用 MP4/WebM、JPG/PNG/WebP、CSV/JSON 或 Google 表格。Excel／PDF 成绩可导出 CSV 或清晰截图。',
    file_too_large: '文件超出大小限制，请压缩或拆分后重新分享。', empty_file: '分享文件没有内容。', download_failed: '下载超时或中断，请重试或缩小文件。',
    invalid_data: '找不到有效的数值成绩，请核对 CSV／JSON 格式或使用模板。', columns_required: '数据需要 metric 及 value 字段，请使用 CSV 模板。', too_many_metrics: '每次最多提交 200 个指标。',
    unauthenticated: '登录已失效，请重新登录。', setup_required: '成绩存储尚未启用，请联系管理员。', storage_failed: '未能保存报告，请重试。', rate_limit: '提交过于频繁，请稍后再试（每 10 分钟 5 次，每天 30 次）。',
    invalid_request: '请填写名称、链接、科目并确认处理同意。', analysis_failed: 'AI 分析未完成，已保留提交记录，可以重试。',
    ai_unavailable: '所需的 AI 模型尚未配置，请联系管理员；数据预览仍可查看。', analysis_busy: '分析正在进行，或此记录已达 3 次尝试上限。',
    invalid_frames: '提取的画面无效，请重新读取视频后再试。', not_found: '此账号无法访问该报告。', video_decode: '浏览器无法解码文件。请将视频转成 MP4/H.264，或使用 JPG／PNG 截图。', video_duration: '请使用长度可读取且不超过 20 分钟的视频。',
    invalid_value: '缺少指标或数字无效', missing_standard: '缺少目标或比较方向'
  },
  ms: {
    flightTitle: 'Keputusan latihan penerbangan', flightType: 'Jenis penerbangan', simulatorMode: 'Simulator', realMode: 'Penerbangan sebenar', screenshot: 'Tangkap layar keputusan', recording: 'Rakaman penerbangan', videoLink: 'Pautan Drive rakaman penerbangan yang sama (pilihan)',
    screenshotHelp: 'Hantar tangkap layar keputusan simulator. AI hanya membaca skor dan metrik yang jelas.', pairHelp: 'Pautan pertama untuk tangkap layar keputusan. Tambah rakaman penerbangan yang sama di bawah untuk satu laporan bersama. Pastikan kedua-duanya daripada penerbangan yang sama.', crossCheck: 'Perbandingan tangkap layar dan video', consistent: 'Bukti kelihatan sepadan', conflict: 'Bukti bercanggah', pair_requires_image: 'Dengan rakaman, pautan pertama mesti tangkap layar keputusan JPG/PNG/WebP.', pair_requires_video: 'Pautan kedua mesti rakaman penerbangan MP4/WebM.',
    extracting: 'Mengekstrak bingkai', numeric: 'Keputusan ukuran', ai: 'Maklum balas AI', metric: 'Metrik', value: 'Nilai ukuran', target: 'Sasaran fail', deviation: 'Perbezaan', status: 'Status', evidence: 'Bukti', advice: 'Latihan seterusnya', limitations: 'Batasan analisis',
    empty: 'Belum ada penyerahan', confirmDelete: 'Padam laporan ini? Fail asal dalam Drive anda akan kekal.', more: 'Muatkan lagi', template: 'Templat CSV', source: 'Fail asal',
    privacy: 'Hanya anda boleh melihat laporan ini dalam AiLAE Class. Sesiapa yang mempunyai pautan awam masih boleh mengakses fail Drive tersebut.',
    reference: 'Untuk rujukan latihan sahaja. Sasaran fail diberikan oleh pelajar, bukan piawaian pengajar yang disahkan. Video dianalisis melalui 12 bingkai pegun tanpa audio, bukan keseluruhan penerbangan atau gred rasmi.',
    formats: 'MP4/H.264 atau WebM: 100 MB, 20 min · JPG/PNG/WebP: 5 MB · CSV/JSON/Google Sheets: 2 MB, 200 metrik',
    guide1: 'Muat naik rakaman, tangkap layar atau fail keputusan ke Google Drive anda.',
    guide2: 'Kongsi fail itu sahaja sebagai “Sesiapa yang mempunyai pautan · Pelihat” dan benarkan muat turun. Buang maklumat peribadi atau sensitif dahulu.',
    guide3: 'Tampal pautan, pilih senario, baca fail dan semak pratonton sebelum meminta analisis AI.',
    guide4: 'Gunakan lajur metric,value,unit,target,direction. Arah: lower (≤), higher (≥) atau equal (=). Eksport Excel sebagai CSV atau kongsi melalui Google Sheets.',
    invalidRows: 'Baris tidak sah', warnings: 'Baris perlu diperiksa', reloadMedia: 'Baca semula pautan Drive untuk menganalisis media ini.', pending: 'Membaca', imported: 'Sedia dianalisis', processing: 'Menganalisis', completed: 'Selesai', failed: 'Gagal', frame: 'Bingkai', issues: 'Kualiti data', retry: 'Cuba lagi',
    invalid_link: 'Gunakan pautan fail Google Drive atau Google Sheets. Pautan folder dan laman lain tidak disokong.',
    share_unavailable: 'Fail tidak dapat dimuat turun. Semak perkongsian pautan untuk pelihat, kebenaran muat turun dan kewujudan fail.',
    unsupported_file: 'Format tidak disokong. Gunakan MP4/WebM, JPG/PNG/WebP, CSV/JSON atau Google Sheets. Eksport Excel/PDF sebagai CSV atau tangkap layar yang jelas.',
    file_too_large: 'Fail melebihi had saiz. Mampatkan atau pecahkan fail sebelum berkongsi semula.', empty_file: 'Fail yang dikongsi kosong.', download_failed: 'Muat turun tamat masa atau terganggu. Cuba fail yang lebih kecil.',
    invalid_data: 'Tiada keputusan berangka yang sah. Semak format CSV/JSON dan gunakan templat.', columns_required: 'Fail memerlukan lajur metric dan value. Gunakan templat CSV.', too_many_metrics: 'Maksimum 200 metrik setiap penyerahan.',
    unauthenticated: 'Sila log masuk semula.', setup_required: 'Storan keputusan belum diaktifkan. Hubungi pentadbir.', storage_failed: 'Laporan tidak dapat disimpan. Cuba lagi.', rate_limit: 'Terlalu banyak penyerahan. Cuba kemudian (5 setiap 10 minit, 30 sehari).',
    invalid_request: 'Lengkapkan nama, pautan, senario dan persetujuan sebelum menghantar.', analysis_failed: 'Analisis AI tidak selesai. Penyerahan disimpan; cuba lagi.', ai_unavailable: 'Model AI belum dikonfigurasi. Hubungi pentadbir; pratonton data masih tersedia.',
    analysis_busy: 'Analisis sedang berjalan atau penyerahan telah mencapai had 3 percubaan.', invalid_frames: 'Bingkai tidak sah. Baca semula video dan cuba lagi.', not_found: 'Laporan ini tidak tersedia untuk akaun anda.',
    video_decode: 'Pelayar tidak dapat menyahkod fail. Tukar video kepada MP4/H.264 atau gunakan tangkap layar JPG/PNG.', video_duration: 'Gunakan video dengan tempoh yang dapat dibaca dan tidak melebihi 20 minit.', invalid_value: 'Metrik tiada atau nombor tidak sah', missing_standard: 'Sasaran atau arah perbandingan tiada'
  },
  id: {
    flightTitle: 'Hasil latihan penerbangan', flightType: 'Jenis penerbangan', simulatorMode: 'Simulator', realMode: 'Penerbangan nyata', screenshot: 'Tangkapan layar hasil', recording: 'Rekaman penerbangan', videoLink: 'Tautan Drive rekaman penerbangan yang sama (opsional)',
    screenshotHelp: 'Kirim tangkapan layar hasil simulator. AI hanya membaca skor dan metrik yang jelas.', pairHelp: 'Tautan pertama untuk tangkapan layar hasil. Tambahkan rekaman penerbangan yang sama di bawah untuk satu laporan bersama. Pastikan keduanya berasal dari penerbangan yang sama.', crossCheck: 'Perbandingan tangkapan layar dan video', consistent: 'Bukti yang terlihat sesuai', conflict: 'Bukti bertentangan', pair_requires_image: 'Dengan rekaman, tautan pertama harus tangkapan layar hasil JPG/PNG/WebP.', pair_requires_video: 'Tautan kedua harus rekaman penerbangan MP4/WebM.',
    extracting: 'Mengekstrak bingkai', numeric: 'Hasil pengukuran', ai: 'Umpan balik AI', metric: 'Metrik', value: 'Nilai terukur', target: 'Target berkas', deviation: 'Selisih', status: 'Status', evidence: 'Bukti', advice: 'Latihan berikutnya', limitations: 'Batasan analisis',
    empty: 'Belum ada kiriman', confirmDelete: 'Hapus laporan ini? Berkas asli di Drive Anda tetap tersimpan.', more: 'Muat lebih banyak', template: 'Templat CSV', source: 'Berkas asli',
    privacy: 'Hanya Anda yang dapat melihat laporan ini di AiLAE Class. Siapa pun yang memiliki tautan publik tetap dapat mengakses berkas Drive tersebut.',
    reference: 'Hanya untuk referensi latihan. Target berkas berasal dari peserta, bukan standar pengajar yang terverifikasi. Analisis video menggunakan 12 bingkai tanpa audio, bukan seluruh penerbangan atau nilai resmi.',
    formats: 'MP4/H.264 atau WebM: 100 MB, 20 menit · JPG/PNG/WebP: 5 MB · CSV/JSON/Google Sheets: 2 MB, 200 metrik',
    guide1: 'Unggah rekaman, tangkapan layar atau berkas hasil ke Google Drive Anda.',
    guide2: 'Bagikan hanya berkas tersebut sebagai “Siapa saja yang memiliki link · Pelihat”, dengan izin mengunduh. Hapus informasi pribadi atau sensitif terlebih dahulu.',
    guide3: 'Tempel tautan, pilih skenario, baca berkas dan periksa pratinjau sebelum meminta analisis AI.',
    guide4: 'Gunakan kolom metric,value,unit,target,direction. Arah: lower (≤), higher (≥) atau equal (=). Ekspor Excel sebagai CSV atau bagikan melalui Google Sheets.',
    invalidRows: 'Baris tidak valid', warnings: 'Baris yang perlu diperiksa', reloadMedia: 'Baca kembali tautan Drive untuk menganalisis media ini.', pending: 'Membaca', imported: 'Siap dianalisis', processing: 'Menganalisis', completed: 'Selesai', failed: 'Gagal', frame: 'Bingkai', issues: 'Kualitas data', retry: 'Coba lagi',
    invalid_link: 'Gunakan tautan berkas Google Drive atau Google Sheets. Tautan folder dan situs lain tidak didukung.',
    share_unavailable: 'Berkas tidak dapat diunduh. Periksa berbagi tautan untuk pelihat, izin unduh dan apakah berkas masih ada.',
    unsupported_file: 'Format tidak didukung. Gunakan MP4/WebM, JPG/PNG/WebP, CSV/JSON atau Google Sheets. Ekspor Excel/PDF sebagai CSV atau tangkapan layar yang jelas.',
    file_too_large: 'Berkas melebihi batas ukuran. Kompres atau pisahkan sebelum membagikan kembali.', empty_file: 'Berkas yang dibagikan kosong.', download_failed: 'Unduhan terputus atau kehabisan waktu. Coba berkas yang lebih kecil.',
    invalid_data: 'Tidak ditemukan hasil numerik yang valid. Periksa format CSV/JSON dan gunakan templat.', columns_required: 'Berkas memerlukan kolom metric dan value. Gunakan templat CSV.', too_many_metrics: 'Maksimal 200 metrik per kiriman.',
    unauthenticated: 'Silakan masuk kembali.', setup_required: 'Penyimpanan hasil belum diaktifkan. Hubungi administrator.', storage_failed: 'Laporan gagal disimpan. Coba lagi.', rate_limit: 'Terlalu banyak kiriman. Coba nanti (5 per 10 menit, 30 per hari).',
    invalid_request: 'Lengkapi nama, tautan, skenario dan persetujuan sebelum mengirim.', analysis_failed: 'Analisis AI belum selesai. Kiriman tersimpan; coba lagi.', ai_unavailable: 'Model AI belum dikonfigurasi. Hubungi administrator; pratinjau data tetap tersedia.',
    analysis_busy: 'Analisis sedang berjalan atau kiriman telah mencapai batas 3 percobaan.', invalid_frames: 'Bingkai tidak valid. Baca kembali video lalu coba lagi.', not_found: 'Laporan ini tidak tersedia untuk akun Anda.',
    video_decode: 'Browser tidak dapat mendekode berkas. Konversi video ke MP4/H.264 atau gunakan tangkapan layar JPG/PNG.', video_duration: 'Gunakan video dengan durasi yang dapat dibaca dan tidak lebih dari 20 menit.', invalid_value: 'Metrik hilang atau angka tidak valid', missing_standard: 'Target atau arah perbandingan tidak tersedia'
  },
  hi: {
    flightTitle: 'उड़ान अभ्यास के परिणाम', flightType: 'उड़ान का प्रकार', simulatorMode: 'सिम्युलेटर', realMode: 'वास्तविक उड़ान', screenshot: 'परिणाम का स्क्रीनशॉट', recording: 'उड़ान की रिकॉर्डिंग', videoLink: 'उसी उड़ान की रिकॉर्डिंग का Drive लिंक (वैकल्पिक)',
    screenshotHelp: 'सिम्युलेटर परिणाम का स्क्रीनशॉट भेजें। AI केवल स्पष्ट अंक और मापदंड पढ़ता है।', pairHelp: 'पहले लिंक में परिणाम का स्क्रीनशॉट दें। उसी उड़ान की रिकॉर्डिंग नीचे जोड़कर एक संयुक्त रिपोर्ट बनाएँ। दोनों फ़ाइलें एक ही उड़ान की होनी चाहिए।', crossCheck: 'स्क्रीनशॉट और वीडियो की तुलना', consistent: 'दिखने वाले साक्ष्य मेल खाते हैं', conflict: 'साक्ष्यों में अंतर है', pair_requires_image: 'रिकॉर्डिंग जोड़ते समय पहला लिंक JPG/PNG/WebP परिणाम स्क्रीनशॉट होना चाहिए।', pair_requires_video: 'दूसरा लिंक MP4/WebM उड़ान रिकॉर्डिंग होना चाहिए।',
    extracting: 'फ़्रेम निकाले जा रहे हैं', numeric: 'मापे गए परिणाम', ai: 'AI सुझाव', metric: 'मापदंड', value: 'मापा गया मान', target: 'फ़ाइल का लक्ष्य', deviation: 'अंतर', status: 'स्थिति', evidence: 'साक्ष्य', advice: 'अगला अभ्यास', limitations: 'विश्लेषण की सीमाएँ',
    empty: 'अभी कोई सबमिशन नहीं है', confirmDelete: 'यह रिपोर्ट हटाएँ? आपकी Drive में मूल फ़ाइल बनी रहेगी।', more: 'और लोड करें', template: 'CSV टेम्पलेट', source: 'मूल फ़ाइल',
    privacy: 'AiLAE Class में केवल आप अपनी रिपोर्ट देख सकते हैं। सार्वजनिक लिंक वाला व्यक्ति Drive फ़ाइल को फिर भी खोल सकता है।',
    reference: 'केवल अभ्यास के लिए। फ़ाइल के लक्ष्य विद्यार्थी द्वारा दिए गए हैं, शिक्षक द्वारा सत्यापित नहीं हैं। वीडियो से बिना ऑडियो के 12 स्थिर फ़्रेम लिए जाते हैं; यह पूरी उड़ान का मूल्यांकन या आधिकारिक अंक नहीं है।',
    formats: 'MP4/H.264 या WebM: 100 MB, 20 मिनट · JPG/PNG/WebP: 5 MB · CSV/JSON/Google Sheets: 2 MB, 200 मापदंड',
    guide1: 'रिकॉर्डिंग, परिणाम का स्क्रीनशॉट या डेटा फ़ाइल अपनी Google Drive में अपलोड करें।',
    guide2: 'केवल उस फ़ाइल को “लिंक वाला कोई भी व्यक्ति · दर्शक” के रूप में साझा करें और डाउनलोड की अनुमति दें। पहले व्यक्तिगत और संवेदनशील जानकारी हटा दें।',
    guide3: 'लिंक पेस्ट करें, अभ्यास चुनें, फ़ाइल पढ़ें और AI विश्लेषण से पहले पूर्वावलोकन जाँचें।',
    guide4: 'कॉलम metric,value,unit,target,direction रखें। दिशा: lower (≤), higher (≥) या equal (=)। Excel को CSV में निर्यात करें या Google Sheets से साझा करें।',
    invalidRows: 'अमान्य पंक्तियाँ', warnings: 'जाँच की आवश्यकता वाली पंक्तियाँ', reloadMedia: 'इस मीडिया का विश्लेषण करने के लिए Drive लिंक दोबारा पढ़ें।', pending: 'पढ़ा जा रहा है', imported: 'विश्लेषण के लिए तैयार', processing: 'विश्लेषण जारी है', completed: 'पूर्ण', failed: 'विफल', frame: 'फ़्रेम', issues: 'डेटा गुणवत्ता', retry: 'फिर से कोशिश करें',
    invalid_link: 'Google Drive फ़ाइल या Google Sheets का लिंक दें। फ़ोल्डर और अन्य वेबसाइट समर्थित नहीं हैं।',
    share_unavailable: 'फ़ाइल डाउनलोड नहीं हुई। दर्शक लिंक साझाकरण, डाउनलोड अनुमति और फ़ाइल की उपलब्धता जाँचें।',
    unsupported_file: 'यह प्रारूप समर्थित नहीं है। MP4/WebM, JPG/PNG/WebP, CSV/JSON या Google Sheets उपयोग करें। Excel/PDF को CSV या स्पष्ट स्क्रीनशॉट में बदलें।',
    file_too_large: 'फ़ाइल आकार सीमा से बड़ी है। संपीड़ित या विभाजित करके फिर साझा करें।', empty_file: 'साझा फ़ाइल खाली है।', download_failed: 'डाउनलोड में समय सीमा समाप्त हुई या बाधा आई। छोटी फ़ाइल आज़माएँ।',
    invalid_data: 'मान्य संख्यात्मक परिणाम नहीं मिले। CSV/JSON प्रारूप जाँचें और टेम्पलेट उपयोग करें।', columns_required: 'metric और value कॉलम आवश्यक हैं। CSV टेम्पलेट उपयोग करें।', too_many_metrics: 'प्रति सबमिशन अधिकतम 200 मापदंड।',
    unauthenticated: 'कृपया फिर से साइन इन करें।', setup_required: 'परिणामों का संग्रह अभी सक्षम नहीं है। व्यवस्थापक से संपर्क करें।', storage_failed: 'रिपोर्ट सहेजी नहीं गई। फिर कोशिश करें।', rate_limit: 'बहुत अधिक सबमिशन हैं। बाद में कोशिश करें (10 मिनट में 5, एक दिन में 30)।',
    invalid_request: 'नाम, लिंक, अभ्यास और सहमति पूरी करें।', analysis_failed: 'AI विश्लेषण पूरा नहीं हुआ। सबमिशन सुरक्षित है; फिर कोशिश करें।', ai_unavailable: 'आवश्यक AI मॉडल कॉन्फ़िगर नहीं है। व्यवस्थापक से संपर्क करें; डेटा पूर्वावलोकन उपलब्ध है।',
    analysis_busy: 'विश्लेषण जारी है या 3 प्रयासों की सीमा पूरी हो गई है।', invalid_frames: 'निकाले गए फ़्रेम अमान्य हैं। वीडियो दोबारा पढ़कर कोशिश करें।', not_found: 'यह रिपोर्ट आपके खाते के लिए उपलब्ध नहीं है।',
    video_decode: 'ब्राउज़र फ़ाइल पढ़ नहीं सकता। वीडियो को MP4/H.264 में बदलें या JPG/PNG स्क्रीनशॉट उपयोग करें।', video_duration: 'पढ़ी जा सकने वाली अवधि वाला अधिकतम 20 मिनट का वीडियो उपयोग करें।', invalid_value: 'मापदंड अनुपस्थित है या संख्या अमान्य है', missing_standard: 'लक्ष्य या तुलना की दिशा अनुपस्थित है'
  },
  th: {
    flightTitle: 'ผลการฝึกบิน', flightType: 'ประเภทการบิน', simulatorMode: 'เครื่องจำลอง', realMode: 'การบินจริง', screenshot: 'ภาพหน้าจอผล', recording: 'วิดีโอการบิน', videoLink: 'ลิงก์ Drive วิดีโอจากเที่ยวบินเดียวกัน (ไม่บังคับ)',
    screenshotHelp: 'ส่งภาพหน้าจอผลจากเครื่องจำลอง AI จะอ่านเฉพาะคะแนนและตัวชี้วัดที่ชัดเจน', pairHelp: 'ลิงก์แรกเป็นภาพหน้าจอผล เพิ่มวิดีโอจากเที่ยวบินเดียวกันด้านล่างเพื่อสร้างรายงานร่วมกัน ตรวจสอบว่าไฟล์ทั้งสองมาจากเที่ยวบินเดียวกัน', crossCheck: 'เปรียบเทียบภาพผลกับวิดีโอ', consistent: 'หลักฐานที่เห็นสอดคล้องกัน', conflict: 'หลักฐานขัดแย้งกัน', pair_requires_image: 'เมื่อแนบวิดีโอ ลิงก์แรกต้องเป็นภาพผล JPG/PNG/WebP', pair_requires_video: 'ลิงก์ที่สองต้องเป็นวิดีโอการบิน MP4/WebM',
    extracting: 'กำลังดึงภาพ', numeric: 'ผลการวัด', ai: 'ข้อเสนอแนะจาก AI', metric: 'ตัวชี้วัด', value: 'ค่าที่วัดได้', target: 'เป้าหมายในไฟล์', deviation: 'ผลต่าง', status: 'สถานะ', evidence: 'หลักฐาน', advice: 'การฝึกครั้งถัดไป', limitations: 'ข้อจำกัดการวิเคราะห์',
    empty: 'ยังไม่มีรายการส่ง', confirmDelete: 'ลบรายงานนี้หรือไม่? ไฟล์ต้นฉบับใน Drive จะยังอยู่', more: 'โหลดเพิ่มเติม', template: 'แม่แบบ CSV', source: 'ไฟล์ต้นฉบับ',
    privacy: 'เฉพาะคุณเท่านั้นที่ดูรายงานนี้ใน AiLAE Class ได้ แต่ผู้ที่มีลิงก์สาธารณะยังเข้าถึงไฟล์ Drive ได้',
    reference: 'สำหรับฝึกฝนเท่านั้น เป้าหมายในไฟล์มาจากผู้เรียน ไม่ใช่มาตรฐานที่ครูรับรอง วิดีโอใช้ภาพนิ่งตัวอย่าง 12 ภาพโดยไม่วิเคราะห์เสียง ไม่ใช่การประเมินเที่ยวบินทั้งหมดหรือคะแนนทางการ',
    formats: 'MP4/H.264 หรือ WebM: 100 MB, 20 นาที · JPG/PNG/WebP: 5 MB · CSV/JSON/Google Sheets: 2 MB, 200 ตัวชี้วัด',
    guide1: 'อัปโหลดวิดีโอ ภาพหน้าจอผล หรือไฟล์ข้อมูลไปยัง Google Drive ของคุณ',
    guide2: 'แชร์เฉพาะไฟล์นั้นเป็น “ทุกคนที่มีลิงก์ · ผู้มีสิทธิ์อ่าน” และอนุญาตให้ดาวน์โหลด ลบข้อมูลส่วนตัวหรือข้อมูลละเอียดอ่อนก่อน',
    guide3: 'วางลิงก์ เลือกสถานการณ์ อ่านไฟล์และตรวจสอบตัวอย่างก่อนขอให้ AI วิเคราะห์',
    guide4: 'ใช้คอลัมน์ metric,value,unit,target,direction ทิศทาง: lower (≤), higher (≥) หรือ equal (=) ส่งออก Excel เป็น CSV หรือแชร์ผ่าน Google Sheets',
    invalidRows: 'แถวที่ไม่ถูกต้อง', warnings: 'แถวที่ต้องตรวจสอบ', reloadMedia: 'อ่านลิงก์ Drive อีกครั้งเพื่อวิเคราะห์สื่อนี้', pending: 'กำลังอ่าน', imported: 'พร้อมวิเคราะห์', processing: 'กำลังวิเคราะห์', completed: 'เสร็จแล้ว', failed: 'ล้มเหลว', frame: 'ภาพ', issues: 'คุณภาพข้อมูล', retry: 'ลองอีกครั้ง',
    invalid_link: 'ใช้ลิงก์ไฟล์ Google Drive หรือ Google Sheets ไม่รองรับลิงก์โฟลเดอร์และเว็บไซต์อื่น',
    share_unavailable: 'ดาวน์โหลดไฟล์ไม่ได้ ตรวจสอบการแชร์ลิงก์สำหรับผู้มีสิทธิ์อ่าน สิทธิ์ดาวน์โหลด และว่าไฟล์ยังอยู่',
    unsupported_file: 'ไม่รองรับรูปแบบนี้ ใช้ MP4/WebM, JPG/PNG/WebP, CSV/JSON หรือ Google Sheets ส่งออก Excel/PDF เป็น CSV หรือภาพหน้าจอที่ชัดเจน',
    file_too_large: 'ไฟล์เกินขนาดที่กำหนด กรุณาบีบอัดหรือแบ่งไฟล์แล้วแชร์ใหม่', empty_file: 'ไฟล์ที่แชร์ไม่มีข้อมูล', download_failed: 'การดาวน์โหลดหมดเวลาหรือถูกขัดจังหวะ ลองใช้ไฟล์ที่เล็กลง',
    invalid_data: 'ไม่พบผลตัวเลขที่ถูกต้อง ตรวจสอบรูปแบบ CSV/JSON และใช้แม่แบบ', columns_required: 'ต้องมีคอลัมน์ metric และ value กรุณาใช้แม่แบบ CSV', too_many_metrics: 'ส่งได้สูงสุด 200 ตัวชี้วัดต่อครั้ง',
    unauthenticated: 'กรุณาเข้าสู่ระบบอีกครั้ง', setup_required: 'ยังไม่ได้เปิดใช้ที่เก็บผล กรุณาติดต่อผู้ดูแลระบบ', storage_failed: 'บันทึกรายงานไม่ได้ กรุณาลองอีกครั้ง', rate_limit: 'ส่งบ่อยเกินไป กรุณาลองภายหลัง (5 ครั้งต่อ 10 นาที และ 30 ครั้งต่อวัน)',
    invalid_request: 'กรอกชื่อ ลิงก์ สถานการณ์ และให้ความยินยอมก่อนส่ง', analysis_failed: 'AI วิเคราะห์ไม่สำเร็จ รายการส่งยังอยู่ กรุณาลองอีกครั้ง', ai_unavailable: 'ยังไม่ได้ตั้งค่าโมเดล AI กรุณาติดต่อผู้ดูแลระบบ ยังดูตัวอย่างข้อมูลได้',
    analysis_busy: 'กำลังวิเคราะห์ หรือรายการนี้ครบ 3 ครั้งที่อนุญาตแล้ว', invalid_frames: 'ภาพที่ดึงมาไม่ถูกต้อง อ่านวิดีโอใหม่แล้วลองอีกครั้ง', not_found: 'บัญชีของคุณเข้าถึงรายงานนี้ไม่ได้',
    video_decode: 'เบราว์เซอร์ถอดรหัสไฟล์ไม่ได้ แปลงวิดีโอเป็น MP4/H.264 หรือใช้ภาพหน้าจอ JPG/PNG', video_duration: 'ใช้วิดีโอที่อ่านระยะเวลาได้และยาวไม่เกิน 20 นาที', invalid_value: 'ขาดตัวชี้วัดหรือตัวเลขไม่ถูกต้อง', missing_standard: 'ขาดเป้าหมายหรือทิศทางการเปรียบเทียบ'
  }
};

export function driveCopy(locale: string) { return { ...en, ...(localized[locale] || {}), ...(extra[locale] || {}) }; }
