CREATE TABLE IF NOT EXISTS public.payment_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference text NOT NULL UNIQUE CHECK (reference ~ '^FPS-[0-9]{6}-[A-F0-9]{10}$'),
  payer_profile_id uuid NOT NULL REFERENCES public.profile(id) ON DELETE RESTRICT,
  payer_email text NOT NULL,
  organization_id uuid REFERENCES public.organization(id) ON DELETE SET NULL,
  amount_minor bigint NOT NULL CHECK (amount_minor BETWEEN 1 AND 100000000),
  currency text NOT NULL DEFAULT 'HKD' CHECK (currency = 'HKD'),
  payment_method text NOT NULL DEFAULT 'fps' CHECK (payment_method = 'fps'),
  status text NOT NULL DEFAULT 'awaiting_payment'
    CHECK (status IN ('awaiting_payment', 'receipt_submitted', 'verified', 'rejected', 'cancelled', 'expired')),
  receipt_path text,
  receipt_content_type text,
  receipt_original_name text,
  submitted_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid REFERENCES public.profile(id) ON DELETE SET NULL,
  review_note text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payment_orders_payer_created_idx
  ON public.payment_orders (payer_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS payment_orders_status_created_idx
  ON public.payment_orders (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.payment_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES public.payment_orders(id) ON DELETE RESTRICT,
  actor_profile_id uuid REFERENCES public.profile(id) ON DELETE SET NULL,
  action text NOT NULL,
  from_status text,
  to_status text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS payment_audit_logs_order_created_idx
  ON public.payment_audit_logs (order_id, created_at ASC);

ALTER TABLE public.payment_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_audit_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.payment_orders FROM anon, authenticated;
REVOKE ALL ON public.payment_audit_logs FROM anon, authenticated;
GRANT ALL ON public.payment_orders TO service_role;
GRANT SELECT ON public.payment_audit_logs TO service_role;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.payment_audit_logs FROM service_role;

CREATE OR REPLACE FUNCTION public.create_payment_order_secure(
  p_reference text,
  p_payer_profile_id uuid,
  p_payer_email text,
  p_organization_id uuid,
  p_amount_minor bigint,
  p_expires_at timestamptz
) RETURNS SETOF public.payment_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  created_order public.payment_orders;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_payer_profile_id::text, 0));
  IF p_organization_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.organizationmember
    WHERE organization_id = p_organization_id
      AND profile_id = p_payer_profile_id
      AND verified = true
  ) THEN
    RAISE EXCEPTION 'PAYMENT_ORGANIZATION_ACCESS_DENIED';
  END IF;
  IF (SELECT count(*) FROM public.payment_orders
      WHERE payer_profile_id = p_payer_profile_id AND created_at > now() - interval '1 minute') >= 5
     OR (SELECT count(*) FROM public.payment_orders
         WHERE payer_profile_id = p_payer_profile_id AND created_at > now() - interval '1 day') >= 30 THEN
    RAISE EXCEPTION 'PAYMENT_RATE_LIMIT';
  END IF;

  INSERT INTO public.payment_orders (
    reference, payer_profile_id, payer_email, organization_id, amount_minor, expires_at
  ) VALUES (
    p_reference, p_payer_profile_id, lower(p_payer_email), p_organization_id, p_amount_minor, p_expires_at
  ) RETURNING * INTO created_order;

  INSERT INTO public.payment_audit_logs (order_id, actor_profile_id, action, to_status)
  VALUES (created_order.id, p_payer_profile_id, 'order_created', created_order.status);
  RETURN NEXT created_order;
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_payment_receipt_secure(
  p_order_id uuid,
  p_payer_profile_id uuid,
  p_receipt_path text,
  p_receipt_content_type text,
  p_receipt_original_name text
) RETURNS SETOF public.payment_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_order public.payment_orders;
  previous_status text;
BEGIN
  SELECT * INTO current_order FROM public.payment_orders WHERE id = p_order_id FOR UPDATE;
  IF current_order.id IS NULL OR current_order.payer_profile_id <> p_payer_profile_id THEN
    RAISE EXCEPTION 'PAYMENT_ORDER_NOT_FOUND';
  END IF;
  IF current_order.expires_at <= now() OR current_order.status NOT IN ('awaiting_payment', 'rejected') THEN
    RAISE EXCEPTION 'PAYMENT_RECEIPT_NOT_ALLOWED';
  END IF;
  previous_status := current_order.status;

  UPDATE public.payment_orders SET
    receipt_path = p_receipt_path,
    receipt_content_type = p_receipt_content_type,
    receipt_original_name = p_receipt_original_name,
    status = 'receipt_submitted',
    submitted_at = now(),
    reviewed_at = NULL,
    reviewed_by = NULL,
    review_note = '',
    updated_at = now()
  WHERE id = p_order_id
  RETURNING * INTO current_order;

  INSERT INTO public.payment_audit_logs (order_id, actor_profile_id, action, from_status, to_status)
  VALUES (current_order.id, p_payer_profile_id, 'receipt_submitted', previous_status, 'receipt_submitted');
  RETURN NEXT current_order;
END;
$$;

CREATE OR REPLACE FUNCTION public.review_payment_order_secure(
  p_order_id uuid,
  p_reviewer_profile_id uuid,
  p_decision text,
  p_review_note text,
  p_bank_confirmed boolean
) RETURNS SETOF public.payment_orders
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_order public.payment_orders;
BEGIN
  IF p_decision NOT IN ('verified', 'rejected') THEN RAISE EXCEPTION 'PAYMENT_DECISION_INVALID'; END IF;
  IF lower(coalesce((SELECT email FROM public.profile WHERE id = p_reviewer_profile_id), '')) <> 'admin@5gnu.com' THEN
    RAISE EXCEPTION 'PAYMENT_REVIEWER_NOT_AUTHORIZED';
  END IF;
  IF p_decision = 'verified' AND p_bank_confirmed IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'PAYMENT_BANK_CONFIRMATION_REQUIRED';
  END IF;
  SELECT * INTO current_order FROM public.payment_orders WHERE id = p_order_id FOR UPDATE;
  IF current_order.id IS NULL OR current_order.status <> 'receipt_submitted' THEN
    RAISE EXCEPTION 'PAYMENT_REVIEW_NOT_ALLOWED';
  END IF;

  UPDATE public.payment_orders SET
    status = p_decision,
    reviewed_at = now(),
    reviewed_by = p_reviewer_profile_id,
    review_note = left(coalesce(p_review_note, ''), 1000),
    updated_at = now()
  WHERE id = p_order_id
  RETURNING * INTO current_order;

  INSERT INTO public.payment_audit_logs (order_id, actor_profile_id, action, from_status, to_status, metadata)
  VALUES (
    current_order.id,
    p_reviewer_profile_id,
    'admin_reviewed',
    'receipt_submitted',
    p_decision,
    jsonb_build_object('bank_statement_confirmed', p_bank_confirmed)
  );
  RETURN NEXT current_order;
END;
$$;

CREATE OR REPLACE FUNCTION public.expire_stale_payment_orders_secure(
  p_payer_profile_id uuid,
  p_include_all boolean DEFAULT false
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  stale_order record;
  expired_count integer := 0;
BEGIN
  FOR stale_order IN
    SELECT id, payer_profile_id, status
    FROM public.payment_orders
    WHERE expires_at <= now()
      AND status IN ('awaiting_payment', 'rejected')
      AND (p_include_all OR payer_profile_id = p_payer_profile_id)
    FOR UPDATE
  LOOP
    UPDATE public.payment_orders SET status = 'expired', updated_at = now() WHERE id = stale_order.id;
    INSERT INTO public.payment_audit_logs (order_id, actor_profile_id, action, from_status, to_status)
    VALUES (stale_order.id, p_payer_profile_id, 'order_expired', stale_order.status, 'expired');
    expired_count := expired_count + 1;
  END LOOP;
  RETURN expired_count;
END;
$$;

CREATE OR REPLACE FUNCTION public.expire_payment_order_secure(
  p_order_id uuid,
  p_actor_profile_id uuid
) RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  previous_status text;
BEGIN
  SELECT status INTO previous_status FROM public.payment_orders
  WHERE id = p_order_id AND payer_profile_id = p_actor_profile_id FOR UPDATE;
  IF previous_status IN ('awaiting_payment', 'rejected') THEN
    UPDATE public.payment_orders SET status = 'expired', updated_at = now() WHERE id = p_order_id;
    INSERT INTO public.payment_audit_logs (order_id, actor_profile_id, action, from_status, to_status)
    VALUES (p_order_id, p_actor_profile_id, 'order_expired', previous_status, 'expired');
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.create_payment_order_secure(text, uuid, text, uuid, bigint, timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.submit_payment_receipt_secure(uuid, uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.review_payment_order_secure(uuid, uuid, text, text, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.expire_payment_order_secure(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.expire_stale_payment_orders_secure(uuid, boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_payment_order_secure(text, uuid, text, uuid, bigint, timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_payment_receipt_secure(uuid, uuid, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.review_payment_order_secure(uuid, uuid, text, text, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_payment_order_secure(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.expire_stale_payment_orders_secure(uuid, boolean) TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'payment-receipts',
  'payment-receipts',
  false,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
ON CONFLICT (id) DO UPDATE SET
  public = false,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

COMMENT ON TABLE public.payment_orders IS
  'Server-mediated FPS payment orders. Client roles have no direct table access.';
COMMENT ON TABLE public.payment_audit_logs IS
  'Append-only history of payment state transitions.';
